spring:
  application:
    name: task-service
  datasource: 
    url: jdbc:mysql://localhost:3306/tasks?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: 1234
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      
server:
  port: 8083 
  
#Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 